// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RunWithMe;

#nullable disable

namespace SD2RunWithMe.Migrations
{
    [DbContext(typeof(HolidayDBContext))]
    [Migration("20230727000021_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("RunWithMe.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a6138ba-89e4-4249-88d3-65c3809bfa8e"),
                            Date = new DateTime(2023, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fourth of July"
                        },
                        new
                        {
                            Id = new Guid("edf6fdb9-86ed-4284-9085-a11370c58f6c"),
                            Date = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Christmas Day"
                        },
                        new
                        {
                            Id = new Guid("279df99d-26bb-48f2-bbdc-63a609691d96"),
                            Date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "April Fools"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
